apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: eflyer
  name: eflyer
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: eflyer
  type: NodePort
status:
  loadBalancer: {}
